// IW7 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init_spawn_factors()
{
    if ( !isdefined( level.spawn_closeenemydistsq ) )
        level.spawn_closeenemydistsq = 250000;

    if ( !isdefined( level.enemyspawninfluencedistsq ) )
        level.enemyspawninfluencedistsq = 810000;

    registerfactor( "avoidShortTimeToEnemySight", ::avoidshorttimetoenemysight, undefined );
    registerfactor( "preferAlliesByDistance", ::preferalliesbydistance, undefined );
    registerfactor( "preferCloseToAlly", ::preferclosetoally, undefined );
    registerfactor( "avoidRecentlyUsedByEnemies", ::avoidrecentlyusedbyenemies, undefined );
    registerfactor( "avoidEnemiesByDistance", ::avoidenemiesbydistance, undefined );
    registerfactor( "avoidEnemyInfluence", ::avoidenemyinfluence, undefined );
    registerfactor( "avoidLastDeathLocation", ::avoidlastdeathlocation, undefined );
    registerfactor( "avoidLastAttackerLocation", ::avoidlastattackerlocation, undefined );
    registerfactor( "avoidShortTimeToJumpingEnemySight", ::avoidshorttimetojumpingenemysight, undefined );
    registerfactor( "avoidVeryShortTimeToJumpingEnemySight", ::avoidveryshorttimetojumpingenemysight, undefined );
    registerfactor( "avoidSameSpawn", ::avoidsamespawn, undefined );
    registerfactor( "avoidRecentlyUsedByAnyone", ::avoidrecentlyusedbyanyone, undefined );
    registerfactor( "randomSpawnScore", ::randomspawnscore, undefined );
    registerfactor( "preferNearLastTeamSpawn", ::prefernearlastteamspawn, undefined );
    registerfactor( "preferClosePoints", ::preferclosepoints, [ "closestPoints" ] );
    registerfactor( "preferShortestDistToKOTHZone", ::prefershortestdisttokothzone, [ "activeKOTHZoneNumber", "maxSquaredDistToObjective" ] );
    registerfactor( "avoidCloseToKOTHZone", ::avoidclosetokothzone, [ "activeKOTHZoneNumber", "kothZoneDeadzoneDistSq" ] );
    registerfactor( "preferDomPoints", ::preferdompoints, [ "preferredDomPoints" ] );
    registerfactor( "avoidClosestEnemy", ::avoidclosestenemy, undefined );
    registerfactor( "avoidClosestEnemyByDistance", ::avoidclosestenemybydistance, [ "closestEnemyInfluenceDistSq" ] );
    registerfactor( "preferClosestToHomeBase", ::preferclosesttohomebase, [ "homeBaseTeam", "maxDistToHomeBase" ] );
    registerfactor( "avoidCloseToBall", ::avoidclosetodefenderflag, [ "activeCarrierPosition", "ballPosition", "avoidBallDeadZoneDistSq" ] );
    registerfactor( "avoidCloseToBallSpawn", ::avoidclosetodefenderflagspawn, [ "avoidBallDeadZoneDistSq" ] );
}

registerfactor( var_0, var_1, var_2 )
{
    if ( !isdefined( level.spawnglobals.factors ) )
        level.spawnglobals.factors = [];

    var_3 = spawnstruct();
    level.spawnglobals.factors[var_0] = var_3;
    var_3.function = var_1;
    var_3.paramreflist = var_2;
}

isfactorregistered( var_0 )
{
    return isdefined( level.spawnglobals.factors[var_0] );
}

getfactorfunction( var_0 )
{
    return level.spawnglobals.factors[var_0].function;
}

getfactorparamreflist( var_0 )
{
    return level.spawnglobals.factors[var_0].paramreflist;
}

calculatefactorscore( var_0, var_1, var_2, var_3 )
{
    var_4 = getfactorfunction( var_1 );
    var_5 = getfactorparamreflist( var_1 );

    if ( isdefined( var_5 ) )
    {
        if ( !isdefined( var_3 ) )
        {

        }

        var_13 = [[ var_4 ]]( var_0, var_3 );
    }
    else
        var_13 = [[ var_4 ]]( var_0 );

    var_13 = clamp( var_13, 0, 100 );
    var_13 = var_13 * var_2;
    var_0.totalpossiblescore = var_0.totalpossiblescore + 100 * var_2;
    var_0.lastscore[self.team] = var_0.lastscore[self.team] + var_13;
    var_0.totalscore = var_0.totalscore + var_13;
    return var_13;
}

critical_factor( var_0, var_1 )
{
    var_2 = [[ var_0 ]]( var_1 );
    var_2 = clamp( var_2, 0, 100 );
    return var_2;
}

avoidcarepackages( var_0 )
{
    foreach ( var_2 in level.carepackages )
    {
        if ( !isdefined( var_2 ) )
            continue;

        if ( distancesquared( var_0.origin, var_2.origin ) < 22500 )
            return 0;
    }

    return 100;
}

avoidgrenades( var_0 )
{
    foreach ( var_2 in level.grenades )
    {
        if ( !isdefined( var_2 ) || !var_2 isexplosivedangeroustoplayer( self ) || scripts\mp\utility::istrue( var_2.shouldnotblockspawns ) )
            continue;

        if ( distancesquared( var_0.origin, var_2.origin ) < 122500 )
            return 0;
    }

    return 100;
}

avoidmines( var_0 )
{
    var_1 = scripts\engine\utility::array_combine( level.mines, level.placedims );

    if ( isdefined( level.traps ) && level.traps.size > 0 )
        var_1 = scripts\engine\utility::array_combine( var_1, level.traps );

    foreach ( var_3 in var_1 )
    {
        if ( !isdefined( var_3 ) || !var_3 isexplosivedangeroustoplayer( self ) || scripts\mp\utility::istrue( var_3.shouldnotblockspawns ) )
            continue;

        if ( distancesquared( var_0.origin, var_3.origin ) < 122500 )
            return 0;
    }

    return 100;
}

isexplosivedangeroustoplayer( var_0 )
{
    if ( !level.teambased || level.friendlyfire || !isdefined( var_0.team ) )
        return 1;
    else
    {
        var_1 = undefined;

        if ( isdefined( self.owner ) )
        {
            if ( var_0 == self.owner )
                return 1;

            var_1 = self.owner.team;
        }

        if ( isdefined( var_1 ) )
            return var_1 != var_0.team;
        else
            return 1;
    }
}

avoidairstrikelocations( var_0 )
{
    if ( !isdefined( level.artillerydangercenters ) )
        return 100;

    if ( !var_0.outside )
        return 100;

    var_1 = scripts\mp\killstreaks\airstrike::getairstrikedanger( var_0.origin );

    if ( var_1 > 0 )
        return 0;

    return 100;
}

avoidcornervisibleenemies( var_0 )
{
    var_1 = "all";

    if ( level.teambased )
        var_1 = scripts\mp\gameobjects::getenemyteam( self.team );

    if ( var_0.cornersights[var_1] > 0 )
        return 0;

    return 100;
}

avoidfullvisibleenemies( var_0 )
{
    var_1 = "all";

    if ( level.teambased )
        var_1 = scripts\mp\gameobjects::getenemyteam( self.team );

    if ( var_0.fullsights[var_1] > 0 )
        return 0;

    return 100;
}

avoidcloseenemies( var_0 )
{
    var_1 = [];
    var_2 = [];

    if ( level.teambased )
        var_1[0] = scripts\mp\gameobjects::getenemyteam( self.team );
    else
        var_1[var_1.size] = "all";

    foreach ( var_4 in var_1 )
    {
        if ( var_0.totalplayers[var_4] == 0 )
            continue;

        var_2[var_2.size] = var_4;
    }

    if ( var_2.size == 0 )
        return 100;

    foreach ( var_4 in var_2 )
    {
        if ( var_0.mindistsquared[var_4] < level.spawn_closeenemydistsq )
            return 0;
    }

    return 100;
}

avoidtelefrag( var_0 )
{
    if ( isdefined( self.allowtelefrag ) )
        return 100;

    if ( positionwouldtelefrag( var_0.origin ) )
    {
        foreach ( var_2 in var_0.alternates )
        {
            if ( !positionwouldtelefrag( var_2 ) )
                return 100;
        }

        return 0;
    }

    return 100;
}

avoidsamespawn( var_0 )
{
    if ( isdefined( self.lastspawnpoint ) && self.lastspawnpoint == var_0 )
        return 0;

    return 100;
}

avoidenemyspawn( var_0 )
{
    if ( isdefined( var_0.lastspawnteam ) && ( !level.teambased || var_0.lastspawnteam != self.team ) )
    {
        var_1 = var_0.lastspawntime + 500;

        if ( gettime() < var_1 )
            return 0;
    }

    return 100;
}

avoidrecentlyusedbyenemies( var_0 )
{
    var_1 = !level.teambased || isdefined( var_0.lastspawnteam ) && self.team != var_0.lastspawnteam;

    if ( var_1 && isdefined( var_0.lastspawntime ) )
    {
        var_2 = gettime() - var_0.lastspawntime;
        var_0.analytics.spawnusedbyenemies = var_2 / 1000;

        if ( var_2 > 4000 )
            return 100;

        return var_2 / 4000 * 100;
    }

    return 100;
}

avoidrecentlyusedbyanyone( var_0 )
{
    if ( isdefined( var_0.lastspawntime ) )
    {
        var_1 = gettime() - var_0.lastspawntime;
        var_0.analytics.timesincelastspawn = var_1 / 1000;

        if ( var_1 > 4000 )
            return 100;

        return var_1 / 4000 * 100;
    }

    return 100;
}

avoidlastdeathlocation( var_0 )
{
    if ( !isdefined( self.lastdeathpos ) )
        return 100;

    var_1 = distancesquared( var_0.origin, self.lastdeathpos );

    if ( var_1 > 810000 )
        return 100;

    var_2 = var_1 / 810000;
    return var_2 * 100;
}

avoidlastattackerlocation( var_0 )
{
    if ( !isdefined( self.lastattacker ) || !isdefined( self.lastattacker.origin ) )
        return 100;

    if ( !scripts\mp\utility::isreallyalive( self.lastattacker ) )
        return 100;

    var_1 = distancesquared( var_0.origin, self.lastattacker.origin );

    if ( var_1 > 810000 )
        return 100;

    var_2 = var_1 / 810000;
    return var_2 * 100;
}

updatefrontline( var_0 )
{
    if ( !updatefrontlineposition() )
        return;

    runfrontlinespawntrapchecks( var_0 );
    updatefrontlinedebug();
}

updatefrontlineposition()
{
    if ( !_id_4BED() )
        return 0;

    var_0 = getglobalfrontlineinfo();
    var_1 = gettime();

    if ( !isdefined( var_0.lastupdatetime ) )
        var_0.lastupdatetime = var_1;
    else if ( var_0.isactive["allies"] && var_0.isactive["axis"] )
        var_0.uptime = var_0.uptime + var_0.lastupdatetimedelta;
    else
        var_0.downtime = var_0.downtime + var_0.lastupdatetimedelta;

    var_2 = ( var_1 - var_0.lastupdatetime ) / 1000.0;
    var_0.lastupdatetime = var_1;
    var_0.lastupdatetimedelta = var_2;
    var_3 = getfrontlineteamcenter( "allies" );

    if ( !isdefined( var_3 ) )
        return 0;

    var_3 = ( var_3[0], var_3[1], 0 );
    var_0.alliesaverage = var_3;
    var_4 = getfrontlineteamcenter( "axis" );

    if ( !isdefined( var_4 ) )
        return 0;

    var_4 = ( var_4[0], var_4[1], 0 );
    var_0.axisaverage = var_4;
    var_5 = var_4 - var_3;
    var_6 = vectortoyaw( var_5 );

    if ( !isdefined( var_0.teamdiffyaw ) || !var_0.isactive["allies"] || !var_0.isactive["axis"] )
        var_0.teamdiffyaw = var_6;

    var_7 = 80.0 * var_2;
    var_8 = var_6 - var_0.teamdiffyaw;

    if ( var_8 > 180 )
        var_8 = var_8 - 360;
    else if ( var_8 < -180 )
        var_8 = 360 + var_8;

    var_7 = clamp( var_8, var_7 * -1, var_7 );
    var_0.teamdiffyaw = var_0.teamdiffyaw + var_7;
    var_9 = var_3 + var_5 * 0.5;

    if ( !isdefined( var_0.midpoint ) || !var_0.isactive["allies"] || !var_0.isactive["axis"] )
        var_0.midpoint = var_9;

    var_10 = var_9 - var_0.midpoint;
    var_11 = length2d( var_10 );
    var_12 = min( var_11, 200.0 * var_2 );

    if ( var_12 > 0 )
    {
        var_10 = var_10 * ( var_12 / var_11 );
        var_0.midpoint = var_0.midpoint + var_10;
    }

    var_13 = anglestoforward( ( 0, var_0.teamdiffyaw, 0 ) );
    var_14 = level.spawnpoints;
    var_14 = scripts\mp\spawnscoring::checkdynamicspawns( var_14 );

    foreach ( var_16 in var_14 )
    {
        var_17 = undefined;
        var_18 = var_0.midpoint - var_16.origin;
        var_19 = vectordot( var_18, var_13 );

        if ( var_19 > 0 )
        {
            var_17 = "allies";
            var_16.frontlineteam = var_17;
            continue;
        }

        var_17 = "axis";
        var_16.frontlineteam = var_17;
    }

    return 1;
}

updatefrontlinedebug()
{
    var_0 = isdefined( level.matchrecording_logevent ) && isdefined( level.matchrecording_generateid );
    var_1 = scripts\mp\analyticslog::analyticslogenabled();

    if ( !var_0 && !var_1 )
        return;

    var_2 = getglobalfrontlineinfo();

    if ( !isdefined( var_2.logids ) && isdefined( level.matchrecording_generateid ) )
    {
        var_2.logids = [];
        var_2.logids["line"] = [[ level.matchrecording_generateid ]]();
        var_2.logids["alliesCenter"] = [[ level.matchrecording_generateid ]]();
        var_2.logids["axisCenter"] = [[ level.matchrecording_generateid ]]();
    }

    if ( !var_2.isactive["allies"] && !var_2.isactive["axis"] )
        return;

    var_3 = ( var_2.midpoint[0], var_2.midpoint[1], level.mapcenter[2] );
    var_4 = anglestoright( ( 0, var_2.teamdiffyaw, 0 ) );
    var_5 = var_3 + var_4 * 5000;
    var_6 = var_3 - var_4 * 5000;

    if ( isdefined( level.matchrecording_logevent ) )
    {
        var_7 = undefined;

        if ( var_2.isactive["allies"] && var_2.isactive["axis"] )
            var_7 = "FRONT_LINE";
        else
            var_7 = scripts\engine\utility::ter_op( var_2.isactive["allies"], "FRONT_LINE_ALLIES", "FRONT_LINE_AXIS" );

        [[ level.matchrecording_logevent ]]( var_2.logids["line"], "allies", var_7, var_5[0], var_5[1], gettime(), undefined, var_6[0], var_6[1] );
    }

    scripts\mp\analyticslog::logevent_frontlineupdate( var_5, var_6, var_2.alliesaverage, var_2.axisaverage, 1 );

    if ( isdefined( level.matchrecording_logevent ) )
    {
        var_8 = scripts\engine\utility::ter_op( var_2.isactive["axis"], var_2.axisaverage, ( 10000, 10000, 10000 ) );
        [[ level.matchrecording_logevent ]]( var_2.logids["axisCenter"], "axis", "ANCHOR", var_8[0], var_8[1], gettime() );
        var_9 = scripts\engine\utility::ter_op( var_2.isactive["allies"], var_2.alliesaverage, ( 10000, 10000, 10000 ) );
        [[ level.matchrecording_logevent ]]( var_2.logids["alliesCenter"], "allies", "ANCHOR", var_9[0], var_9[1], gettime() );
    }
}

getfrontlineteamcenter( var_0 )
{
    var_1 = [];

    foreach ( var_3 in level.players )
    {
        if ( !isdefined( var_3 ) )
            continue;

        if ( !scripts\mp\utility::isreallyalive( var_3 ) )
            continue;

        if ( var_3.team == var_0 )
            var_1[var_1.size] = var_3;
    }

    if ( var_1.size == 0 )
        return undefined;

    var_5 = scripts\mp\utility::getaverageorigin( var_1 );
    return var_5;
}

runfrontlinespawntrapchecks( var_0 )
{
    if ( !_id_4BED() )
        return;

    var_1 = getglobalfrontlineinfo();
    var_1.isactive[var_0] = 1;

    if ( getdvarint( "scr_frontline_trap_checks" ) == 0 )
        return;

    var_2 = getdvarint( "scr_frontline_min_spawns", 0 );

    if ( var_2 == 0 )
        var_2 = 4;

    var_3 = scripts\mp\utility::getotherteam( var_0 );
    var_4 = 0;
    var_5 = level.spawnpoints;
    var_5 = scripts\mp\spawnscoring::checkdynamicspawns( var_5 );

    foreach ( var_7 in var_5 )
    {
        if ( !isdefined( var_7.frontlineteam ) || var_7.frontlineteam != var_0 )
            continue;

        if ( !isdefined( var_7.fullsights ) || !isdefined( var_7.fullsights[var_3] ) || var_7.fullsights[var_3] <= 0 )
            var_4++;
    }

    var_9 = var_4 / var_5.size;

    if ( var_4 < var_2 || var_9 < 0.0 )
    {
        if ( var_4 < var_2 )
            var_1.disabledreason[var_0] = 0;
        else
            var_1.disabledreason[var_0] = 1;

        var_1.isactive[var_0] = 0;
    }
}

_id_4BED()
{
    if ( level.gametype != "war" && level.gametype != "conf" && level.gametype != "cranked" )
        return 0;

    return 1;
}

getglobalfrontlineinfo()
{
    if ( !isdefined( level.frontlineinfo ) )
    {
        level.frontlineinfo = spawnstruct();
        level.frontlineinfo.isactive = [];
        level.frontlineinfo.isactive["allies"] = 0;
        level.frontlineinfo.isactive["axis"] = 0;
        level.frontlineinfo.uptime = 0.0;
        level.frontlineinfo.downtime = 0.0;
    }

    return level.frontlineinfo;
}

preferalliesbydistance( var_0 )
{
    if ( var_0.totalplayers[self.team] == 0 )
        return 0;

    var_1 = var_0.distsumsquared[self.team] / var_0.totalplayers[self.team];
    var_1 = min( var_1, 3240000 );
    var_0.analytics.allyaveragedist = var_1;
    var_2 = 1 - var_1 / 3240000;
    return var_2 * 100;
}

preferclosetoally( var_0 )
{
    var_1 = min( var_0.mindistsquared[self.team], 3240000 );
    var_2 = 1 - var_1 / 3240000;
    return var_2 * 100;
}

avoidenemiesbydistance( var_0 )
{
    var_1 = [];
    var_2 = [];

    if ( level.teambased )
        var_1[0] = scripts\mp\gameobjects::getenemyteam( self.team );
    else
        var_1[var_1.size] = "all";

    foreach ( var_4 in var_1 )
    {
        if ( var_0.totalplayers[var_4] == 0 )
            continue;

        var_2[var_2.size] = var_4;
    }

    if ( var_2.size == 0 )
        return 100;

    foreach ( var_4 in var_2 )
    {
        if ( var_0.mindistsquared[var_4] < 250000 )
            return 0;
    }

    var_8 = 0;
    var_9 = 0;

    foreach ( var_4 in var_2 )
    {
        var_8 = var_8 + var_0.distsumsquaredcapped[var_4];
        var_9 = var_9 + var_0.totalplayers[var_4];
    }

    var_12 = var_8 / var_9;
    var_12 = min( var_12, 7290000 );
    var_13 = var_12 / 7290000;
    var_0.analytics.enemyaveragedist = var_12;
    return var_13 * 100;
}

avoidenemyinfluence( var_0 )
{
    var_1 = undefined;

    if ( level.teambased )
        var_1 = scripts\mp\gameobjects::getenemyteam( self.team );
    else
        var_1 = "all";

    foreach ( var_3 in var_0._id_5721[var_1] )
    {
        if ( var_3 < level.enemyspawninfluencedistsq )
            return 0;
    }

    return 100;
}

avoidclosestenemy( var_0 )
{
    var_1 = [];
    var_2 = [];

    if ( level.teambased )
        var_1[0] = scripts\mp\gameobjects::getenemyteam( self.team );
    else
        var_1[var_1.size] = "all";

    foreach ( var_4 in var_1 )
    {
        if ( var_0.totalplayers[var_4] == 0 )
            continue;

        var_2[var_2.size] = var_4;
    }

    if ( var_2.size == 0 )
        return 100;

    var_6 = 0;

    foreach ( var_4 in var_2 )
    {
        if ( var_0.mindistsquared[var_4] < 250000 )
            return 0;

        var_8 = min( var_0.mindistsquared[var_4], 3240000 );
        var_9 = var_8 / 3240000;
        var_6 = var_6 + var_9 * 100;
    }

    return var_6 / var_2.size;
}

avoidclosestenemybydistance( var_0, var_1 )
{
    var_2 = var_1["closestEnemyInfluenceDistSq"];
    var_3 = "all";

    if ( level.teambased )
        var_3 = scripts\mp\gameobjects::getenemyteam( self.team );

    if ( var_0.mindistsquared[var_3] < 250000 )
        return 0;

    var_4 = min( var_0.mindistsquared[var_3], var_2 );
    var_5 = var_4 / var_2;
    return var_5 * 100;
}

scoredompoint( var_0 )
{
    var_1 = undefined;

    foreach ( var_3 in level.domflags )
    {
        if ( isdefined( var_3.dompointnumber ) && var_3.dompointnumber == var_0 )
        {
            var_1 = var_3;
            break;
        }
    }

    if ( !isdefined( var_1 ) )
        return 100;

    var_5 = var_1 scripts\mp\gameobjects::getclaimteam();

    if ( var_5 == "none" )
        return 100;
    else
        return 50.0;
}

preferdompoints( var_0, var_1 )
{
    var_2 = var_1["preferredDomPoints"];

    if ( var_2[0] && var_0.dompointa )
        return scoredompoint( 0 );

    if ( var_2[1] && var_0.dompointb )
        return scoredompoint( 1 );

    if ( var_2[2] && var_0.dompointc )
        return scoredompoint( 2 );

    return 0;
}

preferclosepoints( var_0, var_1 )
{
    var_2 = var_1["closestPoints"];

    foreach ( var_4 in var_2 )
    {
        if ( var_0 == var_4 )
            return 100;
    }

    return 0;
}

preferbyteambase( var_0, var_1 )
{
    if ( isdefined( var_0.teambase ) && var_0.teambase == var_1 )
        return 100;

    return 0;
}

avoidshorttimetoenemysight( var_0 )
{
    var_1 = "all";

    if ( level.teambased )
        var_1 = scripts\mp\gameobjects::getenemyteam( self.team );

    var_2 = scripts\engine\utility::ter_op( isdefined( var_0.maxsightvalue ) && isdefined( var_0.maxsightvalue[var_1] ), 1.0 - var_0.maxsightvalue[var_1], 0.0 );
    var_0.analytics.maxenemysightfraction = var_2;
    return ( 1.0 - var_2 ) * 0 + var_2 * 100;
}

avoidshorttimetojumpingenemysight( var_0 )
{
    var_1 = "all";

    if ( level.teambased )
        var_1 = scripts\mp\gameobjects::getenemyteam( self.team );

    var_2 = scripts\engine\utility::ter_op( isdefined( var_0.maxjumpsightvalue ) && isdefined( var_0.maxjumpsightvalue[var_1] ), 1.0 - var_0.maxjumpsightvalue[var_1], 0.0 );
    var_0.analytics.maxjumpingenemysightfraction = var_2;
    return ( 1.0 - var_2 ) * 0 + var_2 * 100;
}

avoidveryshorttimetojumpingenemysight( var_0 )
{
    var_1 = "all";

    if ( level.teambased )
        var_1 = scripts\mp\gameobjects::getenemyteam( self.team );

    var_2 = scripts\engine\utility::ter_op( isdefined( var_0.maxjumpsightvalue ) && isdefined( var_0.maxjumpsightvalue[var_1] ), 1.0 - var_0.maxjumpsightvalue[var_1], 0.0 );
    var_3 = var_2 * scripts\mp\spawnlogic::getmaxdistancetolos();

    if ( var_3 < 300 )
        return 0;
    else
        return 100;
}

randomspawnscore( var_0 )
{
    var_0.analytics.randomscore = randomintrange( 0, 99 );
    return var_0.analytics.randomscore;
}

maxplayerspawninfluencedistsquared( var_0 )
{
    return 3240000;
}

prefershortestdisttokothzone( var_0, var_1 )
{
    var_2 = var_1["activeKOTHZoneNumber"];
    var_3 = var_0.distsqtokothzones[var_2];
    var_4 = var_1["maxSquaredDistToObjective"];
    var_5 = 1.0 - var_3 / var_4;
    return 100 * var_5 + 0;
}

avoidclosetokothzone( var_0, var_1 )
{
    var_2 = var_1["activeKOTHZoneNumber"];
    var_3 = var_0.distsqtokothzones[var_2];
    var_4 = var_1["kothZoneDeadzoneDistSq"];
    return scripts\engine\utility::ter_op( var_3 < var_4, 0, 100 );
}

preferclosesttohomebase( var_0, var_1 )
{
    var_2 = var_1["homeBaseTeam"];
    var_3 = var_0.disttohomebase[var_2];
    var_4 = var_1["maxDistToHomeBase"];
    var_5 = var_3 * var_3;
    var_6 = var_4 * var_4;
    var_7 = 1.0 - var_5 / var_6;
    return 100 * var_7 + 0;
}

avoidclosetodefenderflag( var_0, var_1 )
{
    var_2 = undefined;
    var_3 = var_1["activeCarrierPosition"];
    var_4 = var_1["ballPosition"];
    var_5 = var_1["avoidBallDeadZoneDistSq"];

    if ( isdefined( var_3 ) )
        var_2 = var_3;
    else if ( isdefined( var_4 ) )
        var_2 = var_4;

    if ( isdefined( var_2 ) )
    {
        var_6 = distancesquared( var_2, var_0.origin );
        return scripts\engine\utility::ter_op( var_6 < var_5, 0, 100 );
    }
    else
        return 100;
}

avoidclosetodefenderflagspawn( var_0, var_1 )
{
    var_2 = var_0.distsqtoballstart;
    var_3 = var_1["avoidBallDeadZoneDistSq"];
    return scripts\engine\utility::ter_op( var_2 < var_3, 0, 100 );
}

prefernearlastteamspawn( var_0 )
{
    var_1 = level.spawnglobals.lastteamspawnpoints[self.team];

    if ( !isdefined( var_1 ) )
        return 0;

    var_2 = distancesquared( var_1.origin, var_0.origin );
    var_2 = int( min( var_2, 9000000 ) );
    var_3 = 1.0 - var_2 / 9000000;
    return 100 * var_3 + 0;
}
