// IW7 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_id_13F2F( var_0 )
{
    return scripts\aitypes\combat::islowonammo( var_0, 0 );
}

_id_13F30( var_0 )
{
    return scripts\aitypes\common::valuewithinrange( var_0, [ distance( self.origin, self.enemy.origin ), 512, 1024 ] );
}

bindactionscripts()
{
    if ( isdefined( level._id_119E["zombie_grey"] ) )
        return;

    var_0 = spawnstruct();
    var_0.actionfn = [];
    var_0.actionfn[0] = _id_0A14::_id_98C5;
    var_0.actionfn[1] = scripts\aitypes\zombie_grey\behaviors::zombiegreyinitmelee;
    var_0.actionfn[2] = scripts\aitypes\combat_mp::initcombatfunctions_mp;
    var_0.actionfn[3] = scripts\aitypes\zombie_grey\behaviors::zombiegreyinithealthregen;
    var_0.actionfn[4] = scripts\aitypes\zombie_grey\behaviors::zombiegreyinitduplicatingattack;
    var_0.actionfn[5] = scripts\aitypes\zombie_grey\behaviors::zombiegreyinitteleporttoloner;
    var_0.actionfn[6] = scripts\aitypes\zombie_grey\behaviors::zombiegreyinitteleportattack;
    var_0.actionfn[7] = scripts\aitypes\zombie_grey\behaviors::zombiegreyinitteleportsummon;
    var_0.actionfn[8] = scripts\aitypes\zombie_grey\behaviors::zombiegreyinitteleportdash;
    var_0.actionfn[9] = scripts\aitypes\combat::_id_12E90;
    var_0.actionfn[10] = _id_0BFA::_id_3E49;
    var_0.actionfn[11] = _id_0BFA::_id_3DE6;
    var_0.actionfn[12] = scripts\aitypes\combat::isincombat;
    var_0.actionfn[13] = scripts\aitypes\combat::updatelooktarget;
    var_0.actionfn[14] = scripts\aitypes\weapon::_id_12F5C;
    var_0.actionfn[15] = scripts\aitypes\combat::_id_12F28;
    var_0.actionfn[16] = scripts\aitypes\zombie_grey\behaviors::zombiegreyassigntargetplayer;
    var_0.actionfn[17] = scripts\aitypes\zombie_grey\behaviors::zombiegreycheckhealthregen;
    var_0.actionfn[18] = scripts\aitypes\zombie_grey\behaviors::zombiegreyshouldteleportattack;
    var_0.actionfn[19] = scripts\aitypes\zombie_grey\behaviors::zombiegreydoteleportattack;
    var_0.actionfn[20] = scripts\aitypes\zombie_grey\behaviors::zombiegreyshouldteleportdash;
    var_0.actionfn[21] = scripts\aitypes\zombie_grey\behaviors::zombiegreydoteleportdash;
    var_0.actionfn[22] = scripts\aitypes\zombie_grey\behaviors::zombiegreyshouldteleporttoloner;
    var_0.actionfn[23] = scripts\aitypes\zombie_grey\behaviors::zombiegreydoteleporttoloner;
    var_0.actionfn[24] = scripts\aitypes\zombie_grey\behaviors::zombiegreyshouldteleportsummon;
    var_0.actionfn[25] = scripts\aitypes\zombie_grey\behaviors::zombiegreydoteleportsummon;
    var_0.actionfn[26] = scripts\aitypes\zombie_grey\behaviors::zombiegreyshouldduplicatingattack;
    var_0.actionfn[27] = scripts\aitypes\zombie_grey\behaviors::zombiegreydoduplicatingattack;
    var_0.actionfn[28] = _id_0BFA::_id_930A;
    var_0.actionfn[29] = _id_0BFA::_id_930D;
    var_0.actionfn[30] = _id_0BFA::_id_5813;
    var_0.actionfn[31] = _id_0BFA::_id_97FA;
    var_0.actionfn[32] = _id_0BFA::_id_116F3;
    var_0.actionfn[33] = scripts\aitypes\combat::_id_FE88;
    var_0.actionfn[34] = scripts\aitypes\combat::_id_FE6E;
    var_0.actionfn[35] = scripts\aitypes\combat::shoot_terminate;
    var_0.actionfn[36] = scripts\aitypes\common::_id_E475;
    var_0.actionfn[37] = scripts\aitypes\zombie_grey\behaviors::zombiegreyshouldmelee;
    var_0.actionfn[38] = scripts\aitypes\zombie_grey\behaviors::greymeleevsplayer_update;
    var_0.actionfn[39] = scripts\aitypes\zombie_grey\behaviors::greymeleevsplayer_init;
    var_0.actionfn[40] = scripts\aitypes\zombie_grey\behaviors::greymeleevsplayer_terminate;
    var_0.actionfn[41] = scripts\aitypes\combat::_id_8BF6;
    var_0.actionfn[42] = scripts\aitypes\throwgrenade::hasgrenadetimerelapsed;
    var_0.actionfn[43] = scripts\aitypes\combat::_id_B4EB;
    var_0.actionfn[44] = scripts\aitypes\throwgrenade::canthrowgrenade;
    var_0.actionfn[45] = scripts\aitypes\throwgrenade::_id_11812;
    var_0.actionfn[46] = scripts\aitypes\throwgrenade::throwgrenade_init;
    var_0.actionfn[47] = scripts\aitypes\throwgrenade::throwgrenade_terminate;
    var_0.actionfn[48] = scripts\aitypes\zombie_grey\behaviors::zombiegreyhasweapon;
    var_0.actionfn[49] = scripts\aitypes\combat::_id_8BC6;
    var_0.actionfn[50] = ::_id_13F2F;
    var_0.actionfn[51] = ::_id_13F30;
    var_0.actionfn[52] = scripts\aitypes\combat::_id_DF56;
    var_0.actionfn[53] = scripts\aitypes\combat::_id_DF53;
    var_0.actionfn[54] = scripts\aitypes\combat::_id_DF55;
    var_0.actionfn[55] = scripts\aitypes\zombie_grey\behaviors::zombiegreymayshoot;
    var_0.actionfn[56] = scripts\aitypes\combat::_id_8C0B;
    level._id_119E["zombie_grey"] = var_0;
}

registerbehaviortree()
{
    bindactionscripts();
    btregistertree( "zombie_grey" );
}
