// IW7 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

bindactionscripts()
{
    if ( isdefined( level._id_119E["zombie_sasquatch"] ) )
        return;

    var_0 = spawnstruct();
    var_0.actionfn = [];
    var_0.actionfn[0] = scripts\aitypes\zombie_sasquatch\behaviors::sasquatch_init;
    var_0.actionfn[1] = scripts\aitypes\zombie_sasquatch\behaviors::updateeveryframe;
    var_0.actionfn[2] = scripts\aitypes\zombie_sasquatch\behaviors::isintrees;
    var_0.actionfn[3] = scripts\aitypes\zombie_sasquatch\behaviors::shouldtaunt;
    var_0.actionfn[4] = scripts\aitypes\zombie_sasquatch\behaviors::dotaunt;
    var_0.actionfn[5] = scripts\aitypes\zombie_sasquatch\behaviors::taunt_init;
    var_0.actionfn[6] = scripts\aitypes\zombie_sasquatch\behaviors::taunt_cleanup;
    var_0.actionfn[7] = scripts\aitypes\zombie_sasquatch\behaviors::shouldmelee;
    var_0.actionfn[8] = scripts\aitypes\zombie_sasquatch\behaviors::melee_setup;
    var_0.actionfn[9] = scripts\aitypes\zombie_sasquatch\behaviors::melee_charge;
    var_0.actionfn[10] = scripts\aitypes\zombie_sasquatch\behaviors::melee_charge_init;
    var_0.actionfn[11] = scripts\aitypes\zombie_sasquatch\behaviors::melee_charge_cleanup;
    var_0.actionfn[12] = scripts\aitypes\zombie_sasquatch\behaviors::melee_attack;
    var_0.actionfn[13] = scripts\aitypes\zombie_sasquatch\behaviors::melee_attack_init;
    var_0.actionfn[14] = scripts\aitypes\zombie_sasquatch\behaviors::melee_attack_cleanup;
    var_0.actionfn[15] = scripts\aitypes\zombie_sasquatch\behaviors::shouldrush;
    var_0.actionfn[16] = scripts\aitypes\zombie_sasquatch\behaviors::rush_charge;
    var_0.actionfn[17] = scripts\aitypes\zombie_sasquatch\behaviors::rush_charge_init;
    var_0.actionfn[18] = scripts\aitypes\zombie_sasquatch\behaviors::rush_charge_cleanup;
    var_0.actionfn[19] = scripts\aitypes\zombie_sasquatch\behaviors::rush_attack;
    var_0.actionfn[20] = scripts\aitypes\zombie_sasquatch\behaviors::rush_attack_init;
    var_0.actionfn[21] = scripts\aitypes\zombie_sasquatch\behaviors::rush_attack_cleanup;
    var_0.actionfn[22] = scripts\aitypes\zombie_sasquatch\behaviors::shouldthrowrock;
    var_0.actionfn[23] = scripts\aitypes\zombie_sasquatch\behaviors::throwattack;
    var_0.actionfn[24] = scripts\aitypes\zombie_sasquatch\behaviors::throwattack_init;
    var_0.actionfn[25] = scripts\aitypes\zombie_sasquatch\behaviors::throwattack_cleanup;
    var_0.actionfn[26] = scripts\aitypes\zombie_sasquatch\behaviors::wander;
    var_0.actionfn[27] = scripts\aitypes\zombie_sasquatch\behaviors::wander_init;
    var_0.actionfn[28] = scripts\aitypes\zombie_sasquatch\behaviors::wander_cleanup;
    level._id_119E["zombie_sasquatch"] = var_0;
}

registerbehaviortree()
{
    bindactionscripts();
    btregistertree( "zombie_sasquatch" );
}
