// IW7 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

cp_town_onzombiedamaged( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 )
{
    var_12 = self;

    if ( !isdefined( self.agent_type ) )
        return;

    if ( var_4 != "MOD_SUICIDE" )
    {
        if ( scripts\mp\mp_agent::is_friendly_damage( var_12, var_1 ) )
            return;

        if ( scripts\mp\mp_agent::is_friendly_damage( var_12, var_0 ) )
            return;
    }

    if ( !isdefined( var_1 ) )
        var_1 = self;

    var_13 = scripts\cp\agents\gametype_zombie::should_do_damage_checks( var_1, var_2, var_4, var_5, var_8, var_12 );

    if ( !var_13 )
        return;

    var_14 = scripts\engine\utility::is_true( var_12.hit_by_dodging_player );
    var_15 = var_4 == "MOD_MELEE";
    var_16 = scripts\engine\utility::is_true( var_1.inlaststand );
    var_17 = scripts\engine\utility::is_true( var_12.is_suicide_bomber );
    var_3 = var_3 | 4;
    var_18 = isdefined( var_1 ) && isplayer( var_1 );
    var_19 = scripts\engine\utility::isbulletdamage( var_4 ) || var_4 == "MOD_EXPLOSIVE_BULLET" && var_8 != "none";
    var_20 = var_19 && scripts\cp\utility::isheadshot( var_5, var_8, var_4, var_1 );
    var_21 = scripts\engine\utility::is_true( self.battleslid );
    var_22 = scripts\engine\utility::is_true( level.insta_kill ) && !scripts\cp\utility::agentisinstakillimmune();
    var_23 = var_4 == "MOD_EXPLOSIVE_BULLET" && ( isdefined( var_8 ) && var_8 == "none" ) || var_4 == "MOD_EXPLOSIVE" || var_4 == "MOD_GRENADE_SPLASH" || var_4 == "MOD_PROJECTILE" || var_4 == "MOD_PROJECTILE_SPLASH";
    var_24 = !var_16 && var_20 && var_19 && var_1 scripts\cp\utility::is_consumable_active( "headshot_explosion" );
    var_25 = var_15 && var_1 scripts\cp\utility::is_consumable_active( "increased_melee_damage" );
    var_26 = var_15 && var_1 scripts\cp\utility::is_consumable_active( "shock_melee_upgrade" );
    var_27 = scripts\cp\utility::isaltmodeweapon( var_5 );
    var_28 = scripts\cp\utility::agentisfnfimmune();
    var_29 = scripts\cp\utility::agentisinstakillimmune();
    var_30 = var_18 && var_1 scripts\cp\utility::has_zombie_perk( "perk_machine_change" );
    var_31 = scripts\cp\utility::agentisspecialzombie();

    if ( isdefined( var_5 ) && issubstr( var_5, "iw7_gauss_zml" ) )
    {
        var_32 = 250;

        if ( scripts\cp\utility::weaponhasattachment( var_5, "pap1" ) )
            var_32 = 470;

        if ( scripts\cp\utility::weaponhasattachment( var_5, "pap2" ) )
            var_32 = 734;

        if ( scripts\cp\utility::weaponhasattachment( var_5, "doubletap" ) )
            var_32 = 1.33 * var_32;

        if ( var_2 >= var_32 )
            self.hitbychargedshot = var_1;
    }

    if ( var_18 && !var_28 )
    {
        if ( scripts\engine\utility::is_true( self.marked_shared_fate_fnf ) )
            var_1 thread scripts\cp\utility::add_to_notify_queue( "weapon_hit_marked_target", var_1, var_2, var_4, var_5, self );

        self.damaged_by_player = 1;

        if ( scripts\engine\utility::is_true( var_1.stimulus_active ) )
        {
            playfx( level._effect["stimulus_glow_burst"], self gettagorigin( "j_spineupper" ) );
            scripts\engine\utility::play_sound_in_space( "zmb_fnf_stimulus", self gettagorigin( "j_spineupper" ) );

            foreach ( var_34 in level.players )
            {
                if ( var_34 == var_1 )
                {
                    if ( distance2dsquared( var_34.origin, self.origin ) <= 10000 )
                    {
                        playfx( level._effect["stimulus_glow_burst"], self gettagorigin( "j_spineupper" ) );
                        playfx( level._effect["stimulus_shield"], var_34 gettagorigin( "tag_eye" ), anglestoforward( var_34.angles ), anglestoup( var_34.angles ), var_34 );

                        if ( var_2 >= self.health )
                        {
                            if ( scripts\engine\utility::is_true( var_34.inlaststand ) )
                                scripts\cp\zombies\zombies_consumables::revive_downed_entities( var_34 );
                        }

                        if ( var_34.health + var_2 / ( level.players.size + 1 ) >= var_34.maxhealth )
                            var_34.health = var_34.maxhealth;
                        else
                            var_34.health = int( var_34.health + var_2 / ( level.players.size + 1 ) );
                    }

                    continue;
                }

                if ( distance2dsquared( var_34.origin, self.origin ) <= 10000 )
                {
                    playfx( level._effect["stimulus_glow_burst"], self gettagorigin( "j_spineupper" ) );
                    playfx( level._effect["stimulus_shield"], var_34 gettagorigin( "tag_eye" ) );

                    if ( var_2 >= self.health )
                    {
                        if ( scripts\engine\utility::is_true( var_34.inlaststand ) )
                            scripts\cp\zombies\zombies_consumables::revive_downed_entities( var_34 );
                    }

                    if ( int( var_34.health + var_2 / ( level.players.size + 1 ) ) >= var_34.maxhealth )
                    {
                        var_34.health = var_34.maxhealth;
                        continue;
                    }

                    var_34.health = int( var_34.health + var_2 / ( level.players.size + 1 ) );
                }
            }
        }
    }

    if ( isdefined( var_1.is_turned ) && var_1.is_turned && var_4 != "MOD_SUICIDE" )
        var_2 = var_1.melee_damage_amt;

    var_36 = 0;

    if ( !var_15 && scripts\cp\agents\gametype_zombie::checkaltmodestatus( var_5 ) && var_18 && !isdefined( var_1.linked_to_coaster ) && var_1 scripts\cp\utility::is_consumable_active( "sniper_soft_upgrade" ) )
        var_36 = var_1 scripts\cp\utility::coop_getweaponclass( var_5 ) == "weapon_sniper";

    var_37 = !var_28 && scripts\engine\utility::is_true( level.explosive_touch ) && isdefined( var_4 ) && var_4 == "MOD_UNKNOWN";
    var_38 = isdefined( var_5 ) && var_5 == "iw7_knife_zm_cleaver" && iscrog( self );

    if ( isdefined( var_5 ) && var_5 == "iw7_knife_zm_cleaver" && !iscrog( self ) )
        scripts\cp\utility::add_to_notify_queue( "cleaver_damage_zombie" );

    var_39 = !var_29 && ( var_21 || var_22 || var_38 || var_26 || var_37 || var_24 || var_25 || var_36 );
    var_40 = scripts\engine\utility::is_true( self.isfrozen );
    var_41 = var_18 && var_15 && var_1.currentmeleeweapon == "iw7_knife_zm_cleaver";

    if ( var_41 )
    {
        if ( scripts\engine\utility::is_true( self.glowing ) && var_2 >= self.health )
        {
            level.death_by_cleaver = 1;
            level.death_by_cleaver_org = self.origin;
        }
    }

    if ( var_39 && !var_28 )
    {
        if ( var_36 )
            var_1 scripts\cp\utility::notify_used_consumable( "sniper_soft_upgrade" );

        var_2 = int( self.maxhealth );

        if ( var_26 )
        {
            if ( isdefined( var_6 ) )
                playfx( level._effect["shock_melee_impact"], var_6 );

            var_1 thread scripts\cp\zombies\zombie_damage::stun_zap( self geteye(), self, self.maxhealth, "MOD_UNKNOWN", undefined, var_26 );
        }

        if ( var_19 )
            var_1 thread scripts\cp\utility::add_to_notify_queue( "weapon_hit_enemy", self, var_1, var_5, var_2, var_8, var_4 );
    }
    else
    {
        var_8 = scripts\cp\agents\gametype_zombie::shitloc_mods( var_1, var_4, var_5, var_8 );
        var_42 = level.wave_num;
        var_43 = scripts\cp\agents\gametype_zombie::is_grenade( var_5, var_4 );
        var_44 = scripts\engine\utility::is_true( self.is_burning ) && !var_19;
        var_45 = var_20 && var_1 scripts\cp\utility::is_consumable_active( "sharp_shooter_upgrade" );
        var_46 = var_19 && var_1 scripts\cp\utility::is_consumable_active( "bonus_damage_on_last_bullets" );
        var_47 = var_19 && var_1 scripts\cp\utility::is_consumable_active( "damage_booster_upgrade" );
        var_48 = var_19 && isdefined( var_1.special_ammo_weapon ) && var_1.special_ammo_weapon == var_5;
        var_49 = var_18 && var_1 scripts\cp\utility::has_zombie_perk( "perk_machine_boom" );
        var_50 = var_18 && var_1 scripts\cp\utility::has_zombie_perk( "perk_machine_smack" );
        var_51 = scripts\engine\utility::array_contains( level.melee_weapons, var_5 );
        var_52 = weaponclass( var_5 ) == "spread" && var_1 scripts\cp\cp_weapon::has_attachment( var_5, "smart" );
        var_53 = weaponclass( var_5 ) == "spread" && !var_52 && ( var_1 scripts\cp\cp_weapon::has_attachment( var_5, "arkpink" ) || scripts\cp\cp_weapon::has_attachment( var_5, "arkyellow" ) );
        var_54 = var_20 && var_19 && var_1 scripts\cp\cp_weapon::has_attachment( var_5, "highcal" );

        if ( issubstr( var_5, "cutie" ) && var_18 )
        {
            var_55 = 7000;
            self.ragdollhitloc = var_8;

            if ( !isdefined( var_7 ) )
                var_7 = vectornormalize( self.origin - var_1.origin );

            if ( lengthsquared( var_7 ) < 1 )
            {
                var_56 = self.origin - var_1.origin;
                var_56 = vectornormalize( ( var_56[0], var_56[1], var_56[2] ) );
                self.ragdollimpactvector = var_56 * var_55;
            }
            else
                self.ragdollimpactvector = var_7 * var_55;
        }

        if ( var_27 && issubstr( var_5, "+gl" ) )
            var_2 = scripts\cp\agents\gametype_zombie::scalegldamage( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 );

        if ( var_52 )
            var_2 = var_2 * 0.5;

        var_2 = scripts\cp\agents\gametype_zombie::initial_weapon_scale( undefined, var_1, var_2, undefined, var_4, var_5, undefined, undefined, var_8, undefined, undefined, undefined );

        if ( var_53 )
            var_2 = var_2 * 4;

        if ( var_18 )
        {
            if ( var_15 )
            {
                var_2 = int( var_2 * var_1 scripts\cp\perks\perk_utility::perk_getmeleescalar() );

                if ( isdefined( var_1.passive_melee_kill_damage ) )
                    var_2 = var_2 + var_1.passive_melee_kill_damage;

                if ( var_50 )
                    var_2 = var_2 + 1500;

                var_57 = 0;

                if ( var_2 >= self.health )
                    var_57 = 1;

                if ( isdefined( var_1.increased_melee_damage ) )
                    var_2 = var_2 + var_1.increased_melee_damage;

                if ( var_51 && var_57 )
                    var_1 thread scripts\cp\utility::add_to_notify_queue( "melee_weapon_hit", var_5, self, var_2 );

                if ( var_50 )
                {
                    if ( var_57 )
                        self.slappymelee = 1;
                }
            }

            if ( var_48 )
                var_1 thread scripts\cp\zombies\zombie_damage::stun_zap( self geteye(), self, var_2, var_4, 128 );

            if ( var_49 && var_23 )
                var_2 = int( var_2 * 2 );

            if ( isdefined( var_1.stimulus_damage_buff ) )
                var_2 = int( var_2 * 4 );
        }

        if ( var_45 )
            var_2 = var_2 * 3.0;

        if ( var_46 )
        {
            var_58 = int( var_1 getweaponammoclip( var_1 getcurrentweapon() ) + 1 );
            var_59 = weaponclipsize( var_1 getcurrentweapon() );

            if ( var_58 <= 4 )
                var_2 = var_2 * 2;
        }

        if ( var_19 && scripts\engine\utility::is_true( var_1.reload_damage_increase ) )
            var_2 = var_2 * 2;

        if ( var_43 )
            var_2 = var_2 * min( 2 + var_42 * 0.5, 10 );

        if ( var_47 && !var_31 )
            var_2 = int( var_2 * 2 );

        if ( var_54 )
            var_2 = var_2 * 1.2;

        if ( var_18 && var_14 && !var_31 )
        {
            if ( !isdefined( self.launched ) )
            {
                var_55 = 7000;
                self.kung_fu_punched = 1;
                self.ragdollhitloc = var_8;

                if ( !isdefined( var_7 ) )
                    var_7 = vectornormalize( self.origin - var_1.origin );

                if ( lengthsquared( var_7 ) < 1 )
                {
                    var_56 = self.origin - var_1.origin;
                    var_56 = vectornormalize( ( var_56[0], var_56[1], var_56[2] ) );
                    self.ragdollimpactvector = var_56 * var_55;
                }
                else
                    self.ragdollimpactvector = var_7 * var_55;

                var_2 = 100000000;
            }
        }
    }

    if ( isdefined( var_1.perk_data ) && var_1.perk_data["damagemod"].bullet_damage_scalar == 2.0 && var_19 )
        var_2 = var_2 * 1.33;

    if ( scripts\engine\utility::is_true( var_1.deadeye_charge ) )
        var_2 = var_2 * 1.25;

    if ( isdefined( level.damage_per_second ) )
    {
        if ( !scripts\engine\utility::flag( "start_tracking_dps" ) )
            scripts\engine\utility::flag_set( "start_tracking_dps" );

        if ( isdefined( level.dpstime ) )
            level.dpstime = gettime();

        if ( isdefined( var_1.total_damage ) )
            var_1.total_damage = var_1.total_damage + var_2;
    }

    var_2 = scripts\cp\agents\gametype_zombie::shouldapplycrotchdamagemultiplier( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 );
    var_2 = scripts\cp\agents\gametype_zombie::fateandfortuneweaponscale( self, var_5, var_2, 0, var_31, 0, 0 );

    if ( isdefined( var_1.special_zombie_damage ) && var_31 )
        var_2 = var_2 * var_1.special_zombie_damage;

    if ( iscrog( self ) && isdefined( level.special_zombie_damage_func ) && isdefined( level.special_zombie_damage_func[self.agent_type] ) )
        var_2 = self [[ level.special_zombie_damage_func[self.agent_type] ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 );

    if ( isdefined( self.hitbychargedshot ) && !( self.health - var_2 < 1 ) )
        self.hitbychargedshot = undefined;

    var_2 = int( min( var_2, self.health ) );

    if ( isplayer( var_1 ) && scripts\cp\utility::is_melee_weapon( var_5, 1 ) )
        playfx( level._effect["melee_impact"], self gettagorigin( "j_neck" ), vectortoangles( self.origin - var_1.origin ), anglestoup( self.angles ), var_1 );

    if ( self.health > 0 && self.health - var_2 <= 0 )
    {
        if ( self.died_poorly )
            self.died_poorly_health = self.health;

        if ( isdefined( self.has_backpack ) )
            scripts\cp\zombies\zombies_pillage::pillageable_piece_lethal_monitor( self, self.has_backpack, var_1 );

        if ( var_18 && var_30 )
        {
            if ( isdefined( self.agent_type ) && self.agent_type == "generic_zombie" )
            {
                if ( var_5 == "iw7_change_chews_zm" )
                {
                    self.nocorpse = 1;
                    self.full_gib = 1;
                }
                else if ( var_20 )
                {
                    var_60 = 50;

                    if ( randomint( 100 ) < var_60 )
                    {
                        switch ( var_1.sub_perks["perk_machine_change"] )
                        {
                            case "perk_machine_change1":
                                playfx( level._effect["cc_head_nuke"], var_6 );
                                playsoundatpos( var_6, "change_chew_nuke_explo" );
                                var_1 thread change_chews_damage_over_time( self, var_1, 96, "explode" );
                                break;
                            case "perk_machine_change2":
                                playfx( level._effect["cc_zap_burst"], var_6 );
                                playsoundatpos( var_6, "change_chew_electric_explo" );
                                var_1 thread change_chews_damage_over_time( self, var_1, 196, "shocked" );
                                break;
                            case "perk_machine_change3":
                                playfx( level._effect["cc_fire_burst"], var_6 );
                                playsoundatpos( var_6, "change_chew_fire_explo" );
                                var_1 thread change_chews_damage_over_time( self, var_1, 128, "burning" );
                                break;
                            case "perk_machine_change4":
                                playfx( level._effect["cc_ice_burst"], var_6 );
                                var_1 thread change_chews_damage_over_time( self, var_1, 128, "frozen" );
                                break;
                            default:
                                break;
                        }
                    }
                }
            }
        }

        if ( isdefined( self.agent_type ) && self.agent_type == "crab_mini" )
        {
            if ( var_4 == "MOD_SUICIDE" )
                self.vignette_nocorpse = 1;
            else
                thread scripts\mp\agents\crab_mini\crab_mini_agent::create_sludge_pool( self.origin );
        }
        else if ( isdefined( self.agent_type ) && self.agent_type == "crab_brute" )
            thread scripts\mp\agents\crab_brute\crab_brute_agent::create_brute_death_fx( self.origin );
    }

    if ( var_18 )
    {
        if ( isdefined( level.updateondamagepassivesfunc ) )
            level thread [[ level.updateondamagepassivesfunc ]]( var_1, var_5, self );

        var_1 thread scripts\cp\utility::add_to_notify_queue( "weapon_hit_enemy", self, var_1, var_5, var_2, var_8, var_4 );
        var_1 thread scripts\cp\agents\gametype_zombie::updatemaghits( getweaponbasename( var_5 ) );

        if ( var_19 )
        {
            if ( !isdefined( var_1.accuracy_shots_on_target ) )
                var_1.accuracy_shots_on_target = 1;
            else
                var_1.accuracy_shots_on_target++;

            scripts\cp\cp_persistence::increment_player_career_shots_on_target( var_1 );
            scripts\cp\zombies\zombie_analytics::log_playershotsontarget( 1, var_1, var_1.accuracy_shots_on_target );
        }

        if ( !isdefined( var_1.shotsontargetwithweapon[getweaponbasename( var_5 )] ) )
            var_1.shotsontargetwithweapon[getweaponbasename( var_5 )] = 1;
        else
            var_1.shotsontargetwithweapon[getweaponbasename( var_5 )]++;
    }

    scripts\cp\zombies\zombies_gamescore::update_agent_damage_performance( var_1, var_2, var_4 );
    scripts\cp\cp_agent_utils::process_damage_rewards( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_12 );

    if ( isdefined( self.agent_type ) && isdefined( level.damage_feedback_overrride ) && isdefined( level.damage_feedback_overrride[self.agent_type] ) )
        [[ level.damage_feedback_overrride[self.agent_type] ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_12 );
    else
        scripts\cp\cp_agent_utils::process_damage_feedback( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_12 );

    scripts\cp\cp_agent_utils::store_attacker_info( var_1, var_2 );
    scripts\cp\zombies\zombies_weapons::special_weapon_logic( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 );

    if ( var_18 )
        thread scripts\cp\agents\gametype_zombie::new_enemy_damage_check( var_1 );

    var_12 [[ level.agent_funcs[var_12.agent_type]["on_damaged_finished"] ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, 0.0, var_10, var_11 );
}

cp_town_onzombiekilled( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    if ( isdefined( self.spawn_fx ) )
        self.spawn_fx delete();

    if ( isdefined( self.scrnfx ) )
    {
        self.scrnfx delete();
        self.scrnfx = undefined;
    }

    if ( scripts\engine\utility::is_true( self.activated_slomo_sphere ) )
        self.activated_slomo_sphere = undefined;

    if ( issubstr( var_4, "iw7_knife" ) && isplayer( var_1 ) && scripts\cp\utility::is_melee_weapon( var_4 ) )
        var_1 thread scripts\cp\agents\gametype_zombie::setandunsetmeleekill( var_1 );
    else if ( ( var_4 == "iw7_axe_zm" || var_4 == "iw7_axe_zm_pap1" || var_4 == "iw7_axe_zm_pap2" ) && isplayer( var_1 ) && scripts\cp\utility::is_melee_weapon( var_4 ) )
        var_1 thread scripts\cp\agents\gametype_zombie::setandunsetmeleekill( var_1 );
    else if ( issubstr( var_4, "golf" ) || issubstr( var_4, "machete" ) || issubstr( var_4, "spiked_bat" ) || issubstr( var_4, "two_headed_axe" ) )
        var_1 thread scripts\cp\agents\gametype_zombie::setandunsetmeleekill( var_1 );

    if ( isdefined( self.linked_to_boat ) )
    {
        self.linked_to_boat.zombie = undefined;
        self.linked_to_boat = undefined;
    }

    if ( !isplayer( var_1 ) )
    {
        if ( isdefined( var_1.name ) )
        {
            if ( var_1.name == var_1.owner.itemtype )
            {
                if ( isdefined( var_1.owner.killswithitem[var_1.owner.itemtype] ) )
                    var_1.owner.killswithitem[var_1.owner.itemtype]++;
            }
        }
    }

    if ( var_4 == "zmb_imsprojectile_mp" )
    {
        for ( var_9 = 0; var_9 < level.gascanownercount; var_9++ )
        {
            if ( isdefined( level.gascanowner[var_9] ) )
            {
                if ( level.gascanowner[var_9].itemtype == "crafted_gascan" )
                {
                    if ( !isdefined( level.gascankills[level.gascanowner[var_9].name] ) )
                    {
                        level.gascankills[level.gascanowner[var_9].name] = 1;
                        continue;
                    }

                    level.gascankills[level.gascanowner[var_9].name]++;
                }
            }
        }
    }

    if ( isplayer( var_1 ) )
    {
        if ( scripts\engine\utility::is_true( self.marked_shared_fate_fnf ) )
        {
            self.marked_shared_fate_fnf = 0;
            var_1.marked_ents = scripts\engine\utility::array_remove( var_1.marked_ents, self );
            var_1 thread scripts\cp\utility::add_to_notify_queue( "weapon_hit_marked_target", var_1, var_2, var_3, var_4, self );
            self setscriptablepartstate( "shared_fate_fx", "inactive", 1 );
        }

        if ( isdefined( var_1.weapon_passive_xp_multiplier ) && var_1.weapon_passive_xp_multiplier > 1 )
            var_1.kill_with_extra_xp_passive = 1;

        var_10 = var_3 == "MOD_EXPLOSIVE_BULLET" && ( isdefined( var_6 ) && var_6 == "none" ) || var_3 == "MOD_EXPLOSIVE" || var_3 == "MOD_GRENADE_SPLASH" || var_3 == "MOD_PROJECTILE" || var_3 == "MOD_PROJECTILE_SPLASH";

        if ( var_10 )
        {
            if ( !isdefined( var_1.explosive_kills ) )
                var_1.explosive_kills = 1;
            else
                var_1.explosive_kills++;

            scripts\cp\cp_persistence::increment_player_career_explosive_kills( var_1 );
        }

        var_1.kills++;
        var_1.weapon_name_log = scripts\cp\utility::getbaseweaponname( var_4 );

        if ( !isdefined( var_1.aggregateweaponkills[var_1.weapon_name_log] ) )
            var_1.aggregateweaponkills[var_1.weapon_name_log] = 1;
        else
            var_1.aggregateweaponkills[var_1.weapon_name_log]++;

        scripts\cp\zombies\zombie_analytics::log_zombiedeath( 1, level.wave_num, var_1, var_4, self.agent_type, self.origin );

        if ( scripts\engine\utility::isbulletdamage( var_3 ) && var_4 != "incendiary_ammo_mp" && var_4 != "slayer_ammo_mp" )
        {
            if ( isdefined( var_6 ) && scripts\cp\utility::isheadshot( var_4, var_6, var_3, var_1 ) )
                self playsoundtoplayer( "zmb_player_achieve_headshot", var_1 );
        }

        if ( isdefined( var_1.itempicked ) )
        {
            foreach ( var_12 in level.powers )
            {
                if ( var_12.weaponuse == var_4 )
                {
                    if ( var_12.weaponuse == var_1.itempicked )
                    {
                        if ( isdefined( var_1.itemkills[var_1.itempicked] ) )
                        {
                            var_1.itemkills[var_1.itempicked]++;
                            continue;
                        }

                        var_1.itemkills[var_1.itempicked] = 1;
                    }
                }
            }
        }

        if ( isdefined( self.soldier ) )
        {
            var_14 = 100;
            var_15 = 3;
            var_16 = self.origin + ( 0, 0, 20 );
            var_17 = ( randomint( 350 ), randomint( 350 ), randomint( 350 ) );
            var_17 = vectornormalize( var_17 ) * var_14;
            var_18 = self launchgrenade( "frag_grenade_zm", var_16, var_17, var_15 );
        }
    }

    if ( isdefined( var_1.team ) )
    {
        if ( var_1.team == "allies" )
        {
            if ( !isplayer( var_1 ) )
            {
                for ( var_9 = 0; var_9 < level.revocatorownercount; var_9++ )
                {
                    if ( !isdefined( level.revocatorkills[level.revocatorowner[var_9].name] ) )
                    {
                        level.revocatorkills[level.revocatorowner[var_9].name] = 1;
                        continue;
                    }

                    level.revocatorkills[level.revocatorowner[var_9].name]++;
                }
            }
        }
    }

    if ( should_reset_scriptable_states_on_death() )
        scripts\cp\zombies\zombie_scriptable_states::turn_off_states_on_death( self );

    if ( scripts\engine\utility::flag_exist( "force_drop_max_ammo" ) && scripts\engine\utility::flag( "force_drop_max_ammo" ) && var_3 != "MOD_SUICIDE" )
    {
        if ( isdefined( level.drop_max_ammo_func ) )
            level thread [[ level.drop_max_ammo_func ]]( self.origin, var_1, "ammo_max" );

        scripts\engine\utility::flag_clear( "force_drop_max_ammo" );
    }

    var_19 = 0;
    var_20 = 0;
    var_21 = 0;
    var_22 = scripts\engine\utility::is_true( self.is_suicide_bomber );

    if ( isdefined( level.updaterecentkills_func ) && isplayer( var_1 ) )
        var_1 thread [[ level.updaterecentkills_func ]]( self, var_4 );

    if ( getweaponbasename( var_4 ) == "iw7_cutie_zm" || getweaponbasename( var_4 ) == "iw7_cutier_zm" && scripts\engine\utility::is_true( self.affectedbyfovdamage ) )
    {
        self playsound( "bullet_atomizer_impact_npc" );

        if ( isdefined( self.body ) )
        {
            self.body thread scripts\cp\agents\gametype_zombie::playbodyfx();
            self.body hide( 1 );
        }

        self.affectedbyfovdamage = undefined;
    }

    if ( scripts\engine\utility::isbulletdamage( var_3 ) && ( getweaponbasename( var_4 ) == "iw7_atomizer_mp" || scripts\engine\utility::is_true( self.atomize_me ) ) || var_3 == "MOD_UNKNOWN" && getweaponbasename( var_4 ) == "iw7_harpoon3_zm" )
    {
        if ( !var_22 && !var_19 && !var_20 && !var_21 && !scripts\cp\utility::agentisfnfimmune() )
        {
            self playsound( "bullet_atomizer_impact_npc" );

            if ( isdefined( self.body ) )
            {
                self.body thread scripts\cp\agents\gametype_zombie::playbodyfx();
                self.body hide( 1 );
            }
        }
    }

    if ( isplayer( var_1 ) )
    {
        if ( isdefined( var_4 ) && var_4 == "iw7_knife_zm_cleaver" )
        {
            if ( iscrog( self ) )
            {
                if ( isdefined( level.crogs_cleaved ) )
                    level.crogs_cleaved++;

                level thread scripts\cp\utility::add_to_notify_queue( "cleaver_kill", self, self.origin, var_4, var_3 );
            }
            else
                level thread scripts\cp\utility::add_to_notify_queue( "cleaver_kill_zombie" );
        }

        var_1 thread scripts\cp\utility::add_to_notify_queue( "zombie_killed", self, self.origin, var_4, var_3 );
    }

    if ( isdefined( level.on_zombie_killed_quests_func ) )
        [[ level.on_zombie_killed_quests_func ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );

    if ( !scripts\cp\agents\gametype_zombie::isonhumanteam( self ) )
    {
        scripts\cp\agents\gametype_zombie::enemykilled( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );

        if ( isdefined( level.onzombiekilledfunc ) )
            [[ level.onzombiekilledfunc ]]( var_1, var_4 );
    }

    var_1 scripts\cp\zombies\zombies_consumables::headshot_reload_check( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );

    if ( isdefined( level.spawnloopupdatefunc ) )
        [[ level.spawnloopupdatefunc ]]( var_1, var_4 );

    if ( isdefined( self.near_medusa ) && !isdefined( self.soul_claimed ) )
    {
        self.soul_claimed = 1;

        if ( isdefined( var_1.itemtype ) )
        {
            if ( var_1.itemtype == "crafted_medusa" )
            {
                if ( !isdefined( var_1.killswithitem[var_1.itemtype] ) )
                    var_1.killswithitem[var_1.itemtype] = 1;
                else
                    var_1.killswithitem[var_1.itemtype]++;
            }
        }

        level thread [[ level.medusa_killed_func ]]( self.origin, self.near_medusa, scripts\engine\utility::is_true( self.dismember_crawl ) );
    }

    if ( isdefined( self.near_crystal ) && !var_22 )
    {
        if ( isdefined( level.closest_crystal_func ) )
            var_23 = level [[ level.closest_crystal_func ]]( self );
        else
            var_23 = undefined;

        if ( isdefined( var_23 ) )
        {
            if ( isdefined( level.crystal_killed_notify ) )
                thread scripts\cp\agents\gametype_zombie::delayminiufocollection( self.origin, var_4, var_23 );
        }
    }

    if ( isdefined( level.quest_death_update_func ) )
        level thread [[ level.quest_death_update_func ]]( self );

    if ( isplayer( var_1 ) && isdefined( level.updateonkillpassivesfunc ) )
        level thread [[ level.updateonkillpassivesfunc ]]( var_4, var_1, self, var_3, var_6 );

    self hudoutlinedisable();

    if ( isdefined( self.anchor ) )
        self.anchor delete();

    if ( isdefined( self.attack_spot ) )
        scripts\cp\zombies\zombie_entrances::release_attack_spot( self.attack_spot );

    self.closest_entrance = undefined;
    self.attack_spot = undefined;
    self.reached_entrance_goal = undefined;
    self.head_is_exploding = undefined;
    self.rocket_feet = undefined;
    self.dischord_spin = undefined;
    self.upgraded_dischord_spin = undefined;
    self.shredder_death = undefined;
    self.near_medusa = undefined;
    scripts\cp\agents\gametype_zombie::process_kill_rewards( var_0, var_1, self, var_6, var_3, var_4 );
    scripts\cp\agents\gametype_zombie::process_assist_rewards( var_1 );
    scripts\cp\cp_weaponrank::try_give_weapon_xp_zombie_killed( var_1, var_4, var_6, var_3, self.agent_type );

    if ( isdefined( level.death_challenge_update_func ) )
        [[ level.death_challenge_update_func ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );
    else
        scripts\cp\cp_challenge::update_death_challenges( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );

    scripts\cp\cp_merits::process_agent_on_killed_merits( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );

    if ( isdefined( var_1.owner ) )
        var_1.owner scripts\cp\utility::bufferednotify( "kill_event_buffered", var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, self.agent_type );
    else if ( isplayer( var_1 ) )
        var_1 scripts\cp\utility::bufferednotify( "kill_event_buffered", var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, self.agent_type );

    scripts\cp\cp_agent_utils::deactivateagent();

    if ( isdefined( level.cp_rave_zombie_death_pos_record_func ) )
        [[ level.cp_rave_zombie_death_pos_record_func ]]( self.origin );

    level thread scripts\cp\utility::add_to_notify_queue( "zombie_killed", self.origin, var_4, var_3, var_1 );
}

should_reset_scriptable_states_on_death()
{
    if ( isdefined( self.agent_type ) )
    {
        switch ( self.agent_type )
        {
            case "crab_brute":
            case "crab_mini":
            case "crab_boss":
                return 0;
        }
    }
    else
        return 0;

    return 1;
}

callback_townzombieplayerdamage( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11 )
{
    var_12 = self;

    if ( !scripts\cp\zombies\zombie_damage::shouldtakedamage( var_2, var_1, var_5, var_3 ) )
        return;

    if ( damage_from_escort_vehicle( var_0, var_4 ) )
        return;

    if ( var_4 == "MOD_SUICIDE" )
    {
        if ( isdefined( level.overcook_func[var_5] ) )
            level thread [[ level.overcook_func[var_5] ]]( var_12, var_5 );
    }

    var_13 = isdefined( var_4 ) && ( var_4 == "MOD_EXPLOSIVE" || var_4 == "MOD_GRENADE_SPLASH" || var_4 == "MOD_PROJECTILE_SPLASH" );
    var_14 = isdefined( var_4 ) && var_4 == "MOD_EXPLOSIVE_BULLET";
    var_15 = scripts\cp\zombies\zombie_damage::isfriendlyfire( self, var_1 );
    var_16 = scripts\cp\utility::is_hardcore_mode();
    var_17 = scripts\cp\utility::has_zombie_perk( "perk_machine_boom" );
    var_18 = scripts\cp\utility::has_zombie_perk( "perk_machine_change" );
    var_19 = isdefined( var_1 );
    var_20 = var_19 && isdefined( var_1.agent_type ) && var_1.agent_type == "generic_zombie";
    var_21 = var_19 && var_1 == self;
    var_22 = ( var_21 || !var_19 ) && var_4 == "MOD_SUICIDE";

    if ( var_19 )
    {
        if ( var_1 == self )
        {
            if ( var_13 )
            {
                var_23 = self getstance();

                if ( var_17 )
                    var_2 = 0;
                else if ( isdefined( self.has_fortified_passive ) && self.has_fortified_passive && ( self issprintsliding() || ( var_23 == "crouch" || var_23 == "prone" ) && self isonground() ) )
                    var_2 = 0;
                else
                    var_2 = scripts\cp\zombies\zombie_damage::get_explosive_damage_on_player( var_0, var_1, var_2, var_3, var_4, var_5 );
            }

            switch ( var_5 )
            {
                case "zmb_fireworksprojectile_mp":
                case "zmb_imsprojectile_mp":
                case "iw7_armageddonmeteor_mp":
                    var_2 = 0;
                    break;
                case "iw7_stunbolt_zm":
                case "iw7_bluebolts_zm":
                case "blackhole_grenade_zm":
                case "blackhole_grenade_mp":
                    var_2 = 25;
                    break;
                default:
                    break;
            }
        }
        else if ( var_15 )
        {
            if ( var_16 )
            {
                if ( scripts\cp\utility::is_ricochet_damage() )
                {
                    if ( isplayer( var_1 ) && isdefined( var_8 ) && var_8 != "shield" )
                    {
                        if ( isdefined( var_0 ) )
                            var_1 dodamage( var_2, var_1.origin - ( 0, 0, 50 ), var_1, var_0, var_4 );
                        else
                            var_1 dodamage( var_2, var_1.origin, var_1 );
                    }

                    var_2 = 0;
                }
            }
            else
                var_2 = 0;
        }
        else if ( var_20 )
        {
            if ( var_4 != "MOD_EXPLOSIVE" && var_12 scripts\cp\utility::is_consumable_active( "burned_out" ) )
            {
                if ( !scripts\engine\utility::is_true( var_1.is_burning ) )
                {
                    var_12 scripts\cp\utility::notify_used_consumable( "burned_out" );
                    var_1 thread scripts\cp\utility::damage_over_time( var_1, var_12, 3, int( var_1.maxhealth + 1000 ), var_4, "incendiary_ammo_mp", undefined, "burning" );
                    var_1.faf_burned_out = 1;
                }
            }

            var_24 = gettime();

            if ( !isdefined( self.last_zombie_hit_time ) || var_24 - self.last_zombie_hit_time > 20 )
                self.last_zombie_hit_time = var_24;
            else
                return;

            if ( scripts\engine\utility::is_true( self.back_shield ) )
            {
                var_25 = ( 0, 0, 0 );

                if ( isdefined( var_7 ) )
                {
                    var_25 = var_7;
                    var_26 = anglestoforward( self.angles ) * -1;
                    var_27 = vectordot( var_26, var_25 );

                    if ( var_27 < -0.25 )
                        return;
                }
            }

            var_28 = 500;

            if ( getdvarint( "zom_damage_shield_duration" ) != 0 )
                var_28 = getdvarint( "zom_damage_shield_duration" );

            if ( isdefined( var_1.last_damage_time_on_player[self.vo_prefix] ) )
            {
                var_29 = var_1.last_damage_time_on_player[self.vo_prefix];

                if ( var_29 + var_28 > gettime() )
                    var_2 = 0;
                else
                    var_1.last_damage_time_on_player[self.vo_prefix] = gettime();
            }
            else
                var_1.last_damage_time_on_player[self.vo_prefix] = gettime();
        }

        if ( var_14 )
        {
            var_23 = self getstance();

            if ( var_17 )
                var_2 = 0;
            else if ( isdefined( self.has_fortified_passive ) && self.has_fortified_passive && ( self issprintsliding() || ( var_23 == "crouch" || var_23 == "prone" ) && self isonground() ) )
                var_2 = 0;
            else if ( !var_16 || var_1 == self && var_8 == "none" )
                var_2 = 0;
        }
    }
    else if ( var_17 && var_4 == "MOD_SUICIDE" )
    {
        if ( var_5 == "frag_grenade_zm" || var_5 == "cluster_grenade_zm" )
            var_2 = 0;
    }
    else
    {
        var_23 = self getstance();

        if ( isdefined( self.has_fortified_passive ) && self.has_fortified_passive && ( self issprintsliding() || ( var_23 == "crouch" || var_23 == "prone" ) && self isonground() ) )
        {
            if ( var_5 == "frag_grenade_zm" || var_5 == "cluster_grenade_zm" )
                var_2 = 0;
        }
    }

    if ( var_4 == "MOD_FALLING" )
    {
        if ( scripts\cp\utility::_hasperk( "specialty_falldamage" ) )
            var_2 = 0;
        else if ( var_2 > 10 )
        {
            if ( var_2 > self.health * 0.15 )
                var_2 = int( self.health * 0.15 );
        }
        else
            var_2 = 0;
    }

    var_30 = 0.0;

    if ( var_19 && var_1 scripts\cp\utility::is_zombie_agent() && scripts\engine\utility::is_true( self.linked_to_player ) )
    {
        if ( self.health - var_2 < 1 )
            var_2 = self.health - 1;
    }

    if ( var_20 || var_21 && !var_22 )
        var_2 = int( var_2 * var_12 scripts\cp\utility::getdamagemodifiertotal() );

    if ( isdefined( self.linked_to_coaster ) )
        var_2 = int( max( self.maxhealth / 2.75, var_2 ) );

    if ( var_12 scripts\cp\utility::is_consumable_active( "secret_service" ) && isalive( var_1 ) )
    {
        var_31 = 0;

        if ( isdefined( var_1.agent_type ) && ( var_1.agent_type == "crab_mini" || var_1.agent_type == "crab_brute" || var_1 scripts\cp\utility::agentisfnfimmune() ) )
            var_31 = 0;
        else if ( isplayer( var_12 ) && isplayer( var_1 ) )
            var_31 = 0;
        else
            var_31 = 1;

        if ( var_31 )
        {
            var_1 thread scripts\cp\crafted_trap_revocator::turn_zombie( var_12 );
            var_12 scripts\cp\utility::notify_used_consumable( "secret_service" );
        }
    }

    var_2 = int( var_2 );

    if ( !var_15 || var_16 )
    {
        scripts\cp\zombies\zombie_damage::finishplayerdamagewrapper( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_30, var_10, var_11 );
        thread scripts\cp\utility::add_to_notify_queue( "player_damaged" );
    }

    scripts\cp\cp_gamescore::update_personal_encounter_performance( "personal", "damage_taken", var_2 );

    if ( var_2 <= 0 )
        return;

    thread scripts\cp\utility::player_pain_vo();
    thread scripts\cp\zombies\zombie_damage::play_pain_photo( self );
    self playlocalsound( "zmb_player_impact_hit" );
    thread scripts\cp\utility::player_pain_breathing_sfx();

    if ( var_18 )
        self notify( "change_chews_damage", var_2, self.health );

    if ( isdefined( var_1 ) )
    {
        thread scripts\cp\cp_hud_util::zom_player_damage_flash();

        if ( isagent( var_1 ) )
        {
            if ( var_2 > self.health )
                var_1.killed_player = 1;

            if ( !isdefined( var_1.damage_done ) )
                var_1.damage_done = 0;
            else
                var_1.damage_done = var_1.damage_done + var_2;

            self.recent_attacker = var_1;

            if ( isdefined( level.current_challenge ) )
                self [[ level.custom_playerdamage_challenge_func ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );
        }
    }
}

damage_from_escort_vehicle( var_0, var_1 )
{
    if ( isdefined( var_0 ) && isdefined( var_0.targetname ) && var_0.targetname == "bomb_vehicle" && isdefined( var_1 ) && var_1 == "MOD_CRUSH" )
        return 1;

    return 0;
}

playbodyfx_ww( var_0, var_1, var_2 )
{
    var_3[0][1]["org"] = self gettagorigin( "j_spinelower" );
    var_3[0][1]["angles"] = self gettagangles( "j_spinelower" );
    var_4 = undefined;
    var_5 = undefined;

    if ( issubstr( var_0, "iw7_harpoon1_zm" ) || issubstr( var_0, "iw7_acid_rain_projectile_zm" ) )
    {
        self hide( 0 );
        var_1.nocorpse = 0;
        var_1.full_gib = 0;
        var_3[0][0]["org"] = self gettagorigin( "j_spineupper" );
        var_3[0][0]["angles"] = self gettagangles( "j_spineupper" );
        var_4 = level._effect["wrecked_cheap"];
        var_5 = level._effect["acid_rain_death"];
    }
    else if ( issubstr( var_0, "iw7_harpoon2_zm" ) )
        var_4 = level._effect["wrecked_by_ben"];
    else
        var_4 = level._effect["wrecked_cheap"];

    foreach ( var_7 in var_3 )
    {
        foreach ( var_9 in var_7 )
        {
            if ( ( issubstr( var_0, "iw7_harpoon1_zm" ) || issubstr( var_0, "iw7_acid_rain_projectile_zm" ) ) && !scripts\engine\utility::is_true( level.played_acid_rain_effect ) )
            {
                level.played_acid_rain_effect = 1;

                if ( isdefined( var_4 ) )
                    playfx( var_4, var_9["org"], anglestoforward( var_9["angles"] ) );

                scripts\engine\utility::waitframe();

                if ( isdefined( var_5 ) )
                {
                    playfx( var_5, var_9["org"] );
                    scripts\engine\utility::waitframe();
                }

                continue;
            }

            if ( ( issubstr( var_0, "iw7_harpoon2_zm" ) || issubstr( var_0, "iw7_harpoon2_zm_stun" ) ) && !scripts\engine\utility::is_true( level.played_ben_franklin_effect ) )
            {
                level.played_ben_franklin_effect = 1;

                if ( isdefined( var_4 ) )
                    playfx( var_4, var_9["org"], anglestoforward( var_9["angles"] ) );

                scripts\engine\utility::waitframe();
                continue;
            }

            if ( isdefined( var_4 ) )
                playfx( var_4, var_9["org"], anglestoforward( var_9["angles"] ) );

            scripts\engine\utility::waitframe();
        }

        wait 0.01;
    }
}

is_kung_fu_punch( var_0, var_1 )
{
    switch ( var_1 )
    {
        case "iw7_fists_zm_tiger":
        case "iw7_fists_zm_snake":
        case "iw7_fists_zm_dragon":
        case "iw7_fists_zm_crane":
            return 1;
        default:
            break;
    }

    return 0;
}

kung_fu_damage_everyone_in_radius( var_0, var_1, var_2, var_3 )
{
    scripts\engine\utility::waitframe();
    var_4 = var_1 * var_1;

    foreach ( var_6 in level.spawned_enemies )
    {
        if ( scripts\engine\utility::is_true( var_6.kung_fu_punched ) )
            continue;

        if ( distancesquared( var_6.origin, var_0 ) < var_4 )
        {
            var_7 = var_6.health + 1000;

            if ( var_3 )
                var_7 = 1;

            var_6 dodamage( var_7, var_2.origin, var_2, var_2, "MOD_MELEE", "iw7_fists_zm_base" );
            scripts\engine\utility::waitframe();
        }
    }
}

flying_ghost_body( var_0, var_1, var_2 )
{
    var_3 = 100;
    var_4 = 20;
    var_5 = vectornormalize( self.origin - var_0.origin ) * var_3 + ( 0, 0, var_4 );
    var_6 = self.origin + var_5;
    var_7 = level._effect["chi_ghost_hit_blue"];

    if ( isdefined( var_0.kung_fu_progression.active_discipline ) )
    {
        var_8 = var_0.kung_fu_progression.active_discipline;

        switch ( var_8 )
        {
            case "crane":
                var_7 = level._effect["chi_ghost_hit_blue"];
                break;
            case "dragon":
                var_7 = level._effect["chi_ghost_hit_yellow"];
                break;
            case "snake":
                var_7 = level._effect["chi_ghost_hit_green"];
                break;
            case "tiger":
                var_7 = level._effect["chi_ghost_hit_red"];
                break;
            default:
                break;
        }
    }

    playfx( var_7, var_6 );
}

crog_processdamagefeedback( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10 )
{
    if ( !scripts\engine\utility::isbulletdamage( var_4 ) )
    {
        if ( scripts\cp\utility::is_trap( var_0, var_5 ) )
            return;

        var_11 = gettime();

        if ( isdefined( var_1.nexthittime ) && var_1.nexthittime > var_11 )
            return;
        else
            var_1.nexthittime = var_11 + 250;
    }

    var_12 = "standard";
    var_13 = undefined;

    if ( var_10.health <= var_2 )
        var_13 = 1;

    var_14 = scripts\cp\utility::isheadshot( var_5, var_8, var_4, var_1 );

    if ( var_14 )
        var_12 = "hitcritical";

    var_15 = scripts\engine\utility::isbulletdamage( var_4 );
    var_16 = var_14 && var_1 scripts\cp\utility::is_consumable_active( "sharp_shooter_upgrade" );
    var_17 = var_15 && var_1 scripts\cp\utility::is_consumable_active( "bonus_damage_on_last_bullets" );
    var_18 = var_15 && var_1 scripts\cp\utility::is_consumable_active( "damage_booster_upgrade" );
    var_19 = scripts\engine\utility::is_true( var_1.inlaststand );
    var_20 = !var_19 && var_14 && var_15 && var_1 scripts\cp\utility::is_consumable_active( "headshot_explosion" );
    var_21 = !scripts\cp\utility::isreallyalive( var_10 ) || isagent( var_10 ) && var_2 >= var_10.health;
    var_22 = var_4 == "MOD_EXPLOSIVE_BULLET" || var_4 == "MOD_EXPLOSIVE" || var_4 == "MOD_GRENADE_SPLASH" || var_4 == "MOD_PROJECTILE" || var_4 == "MOD_PROJECTILE_SPLASH";
    var_23 = var_4 == "MOD_MELEE";

    if ( scripts\engine\utility::is_true( var_10.armor_hit ) )
        var_12 = "hitalienarmor";
    else if ( var_16 || var_17 || var_18 || var_20 )
        var_12 = "card_boosted";
    else if ( isplayer( var_1 ) && var_1 scripts\cp\utility::has_zombie_perk( "perk_machine_boom" ) && var_22 )
        var_12 = "high_damage";
    else if ( isplayer( var_1 ) && var_1 scripts\cp\utility::has_zombie_perk( "perk_machine_smack" ) && var_23 )
        var_12 = "high_damage";
    else if ( isplayer( var_1 ) && var_1 scripts\cp\utility::has_zombie_perk( "perk_machine_rat_a_tat" ) && var_15 )
        var_12 = "high_damage";
    else if ( isplayer( var_1 ) && scripts\engine\utility::is_true( var_1.deadeye_charge ) && var_15 )
        var_12 = "special_weapon";

    if ( isdefined( var_1 ) )
    {
        if ( isdefined( var_1.owner ) )
            var_1.owner thread scripts\cp\cp_damage::updatedamagefeedback( var_12, var_13, var_2, var_10.riotblock );
        else
            var_1 thread scripts\cp\cp_damage::updatedamagefeedback( var_12, var_13, var_2, var_10.riotblock );
    }

    if ( scripts\engine\utility::is_true( self.armor_hit ) )
        self.armor_hit = 0;
}

change_chews_damage_over_time( var_0, var_1, var_2, var_3 )
{
    var_4 = var_2 * var_2;
    var_5 = var_0.origin;
    var_6 = sortbydistance( level.spawned_enemies, var_1.origin );
    var_7 = 0;

    foreach ( var_9 in var_6 )
    {
        if ( var_9 == var_0 )
            continue;

        if ( isdefined( var_9.chew_effect_time ) && var_9.chew_effect_time == gettime() )
            continue;

        if ( isdefined( var_9.agent_type ) && var_9.agent_type != "generic_zombie" )
            continue;

        if ( distancesquared( var_5, var_9.origin ) < var_4 )
        {
            var_9.chew_effect_time = gettime();
            var_7++;

            switch ( var_3 )
            {
                case "frozen":
                    var_9 thread change_chews_frozen_damage( var_1, var_5 );

                    if ( var_7 >= 6 )
                        return;

                    break;
                case "burning":
                    var_9 thread change_chews_fire_damage( var_1, var_5 );

                    if ( var_7 >= 8 )
                        return;

                    break;
                case "shocked":
                    var_9 thread change_chews_shock_damage( var_1, var_5 );

                    if ( var_7 >= 10 )
                        return;

                    break;
                case "explode":
                    var_9 thread change_chews_explosive_damage( var_1, var_5 );

                    if ( var_7 >= 5 )
                        return;

                    break;
                default:
                    break;
            }

            wait 0.1;
            continue;
        }

        wait 0.1;
    }
}

change_chews_frozen_damage( var_0, var_1 )
{
    self endon( "death" );
    self.isfrozen = 1;
    var_2 = self.health;
    self.health = 1;
    wait 10;
    self.isfrozen = undefined;

    if ( var_2 > 0 )
        self.health = var_2;
}

change_chews_fire_damage( var_0, var_1 )
{
    self endon( "death" );

    if ( isalive( self ) && !scripts\engine\utility::is_true( self.marked_for_death ) )
    {
        self.marked_for_death = 1;
        thread scripts\cp\utility::damage_over_time( self, var_0, 5, 1900, undefined, "iw7_fwoosh_zm", 0, "burning", "fwoosh_kill" );
    }
}

change_chews_shock_damage( var_0, var_1 )
{
    self endon( "death" );
    thread scripts\cp\zombies\zombies_perk_machines::zap_over_time( 2, var_0 );
}

change_chews_explosive_damage( var_0, var_1 )
{
    self dodamage( self.health + 1000, var_1, var_0, var_0, "MOD_EXPLOSIVE", "iw7_change_chews_zm" );
}

iscrog( var_0 )
{
    return isdefined( var_0.agent_type ) && ( var_0.agent_type == "crab_brute" || var_0.agent_type == "crab_mini" );
}
